### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by joseluisq** [callmecavs/bricks.js#1]
Amazing stuff !
It would be great that bricks.js may be available on some CDN.

**Comment by callmecavs** [comment]
@joseluisq I'm trying to push forward the "ES next" way of javascript development - module bundling, etc. for that reason, I've only published the library to `npm`, and don't plan on adding CDN support in the future. I appreciate the suggestion though!

**Comment by joseluisq** [comment]
I understand.
In this case I will use it with Browserify. :+1:

**Comment by callmecavs** [comment]
@joseluisq that's what I like to hear!
