### ISSUE TITLE
Support (r)em units for elements width

### ISSUE THREAD

**Issue by nhoizey** [callmecavs/bricks.js#10]
This is great that media queries in the `sizes` parameter can use any unit, but how is it useful if elements width must be in `px`?

It would be really great if we could also use `em` or `rem` for elements widths. Thanks!

**Comment by callmecavs** [comment]
unfortunately, because those units are relative, and this is a library for fixed width elements, they cant be supported. perhaps in a v2!

**Comment by nhoizey** [comment]
I understand. Maybe you should suggest using `px` only in Media Queries also, then, to prevent unfortunate side effects.

**Comment by callmecavs** [comment]
@nhoizey the media query can be in any unit. it's just the width and gutter of the columns that need to be in px

**Comment by PascalPixel** [comment]
@callmecavs On mobile, I want a single column with 100% width of items;
Can I simply turn bricks off somehow?
Currently all I can think of is making 768 size array items?
