### ISSUE TITLE
Should add a destroy public method

### ISSUE THREAD

**Issue by JSteunou** [callmecavs/bricks.js#11]
In order to clean up things nicely and avoid memory leak due to binding on `resize` event. This is mostly for dynamic webapp.

**Comment by callmecavs** [comment]
@JSteunou any suggestions on how to implement it? because the library sets inline styles, it's a bit difficult to do without side effects. the `data-packed` attribute can be removed without consequence. but removing styles causes problems. the way I see it, there are 2 options:
1. removing the `style` attribute on all the grid elements - this might interfere with other libraries or other inline styles though
2. set all CSS properties that Bricks touches (position, top, left) to their default values - though these styles would be inline, and might interfere with any CSS from stylesheets

**Comment by JSteunou** [comment]
Ho I was not thinking on a _revert_ kind of thing. More a _destroy_ that clean up bindings (seems only resize).

My use case is with Marionette. I though about using brick.js inside a view, and when the view gets destroyed, I usually clean up to avoid memory leaks. Marionette handles a lot of clean up, but if I use a jquery plugin for example, I got to be sure no events bindings are still up. The same applies to brick.js

So it is mostly

``` js
function destroy() {
    window.removeEventListener('resize', resizeFrame);
}
```

**Comment by callmecavs** [comment]
@JSteunou gotcha, my bad, misunderstood. what I'll likely do is make the `resize` method accept a boolean. true to add the handlers, false to remove them.

**Comment by JSteunou** [comment]
That'll also work :)

**Comment by callmecavs** [comment]
@JSteunou this has been fixed in the new [release](https://github.com/callmecavs/bricks.js/releases/tag/v1.1.0). thanks for the suggestion/contribution!

**Comment by JSteunou** [comment]
I did not use bricks.js before so it wont impact me, but I think you introduced a breaking change without using major semver release.

Those using `resize` without argument before will invoke `removeEventListener` instead of `addEventListener`.

Better check on `flag === false` explicitly so those giving `true` or nothing get `addEventListener`. Cherry on the cake, log message saying calling `resize` without arguments is deprecated and will be removed in 2.0.0

Welcome to the javascript semver libraries world :)

**Comment by callmecavs** [comment]
good point, i'll release a bug fix that makes the flag default to true so as to not make this a breaking change.

**Comment by callmecavs** [comment]
@JSteunou the flag now [defaults to true](https://github.com/callmecavs/bricks.js/blob/master/src/bricks.js#L163) in v1.1.1, so this should address breaking the API compatibility. thanks for the heads up, good call

**Comment by JSteunou** [comment]
Nicely done, ES6 is really a good thing for those case :)

**Comment by callmecavs** [comment]
yeah haha, saved by ES6 again
