### ISSUE TITLE
Provide non min file in dist

### ISSUE THREAD

**Issue by JSteunou** [callmecavs/bricks.js#13]
I minify my app and minifying an already minified file is not advised, webpack raise a warning for that.

**Comment by callmecavs** [comment]
@JSteunou definitely plan on doing so, in a future release

**Comment by simon-am** [comment]
That'd be great

**Comment by simon-am** [comment]
Any update on this?

**Comment by callmecavs** [comment]
@JSteunou @simon-am addressed in the latest release - all dist files are non-minified (and there's and ES6 imports/exports version for tree-shaking module bundlers like rollup and webpack2)
