### ISSUE TITLE
animation when viewport resizes ? 

### ISSUE THREAD

**Issue by neuropass** [callmecavs/bricks.js#19]
Is there a way to have the bricks animate into their position when the viewport resizes? Can this be done via CC3 or must be a JS thing?

**Comment by callmecavs** [comment]
**Bricks** positions elements using the `top` and `left` CSS properties, in combination with `position: absolute`. Setting a CSS `transition` on those properties will cause the grid items to animate into place when resizing.

You can make use of the [`resize`](https://github.com/callmecavs/bricks.js#resizeflag) event to run whatever JavaScript you'd like as well.
