### ISSUE TITLE
IE 9 support?

### ISSUE THREAD

**Issue by ahmed1490** [callmecavs/bricks.js#2]
Do you have plans to support IE9 in future?

**Comment by callmecavs** [comment]
unfortunately no, but take a look at the [browser support section](https://github.com/callmecavs/bricks.js#browser-support). if you polyfill the methods listed there that IE9 doesn't support, you ought to be able to make it work relatively painlessly

also in that section is this [link](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills) to Modernizr's list of recommended polyfills/shims/etc
