### ISSUE TITLE
usable as simple js script?

### ISSUE THREAD

**Issue by donlencho** [callmecavs/bricks.js#20]
Hello,
This is more of a question than an issue, but being relatively new to web development and JavaScript, I've never used such an environment to build my websites, only simple js scripts loaded externally or inside my pages.
Also I'm considering using Bricks for a small website for which I don't have access to the server apart from an FTP access, so I won't be able to run any command.
Is there a way to use it for such a use case?
Thank you very much, I hope someone can help me, Bricks seems perfect for what I want to do.

**Comment by callmecavs** [comment]
@donlencho you can [download the `dist` file](https://github.com/callmecavs/bricks.js/blob/master/dist/bricks.min.js) and save it as a `.js` file. Then include it with a `<script>` tag, like you're used to. That output file is already transpiled and minified, so you dont need to run it through a build system, and can upload it to the server as is. Hope that helps!

**Comment by donlencho** [comment]
thanks, will try!
