### ISSUE TITLE
iOS Safari bug on demo page

### ISSUE THREAD

**Issue by andrey-hohlov** [callmecavs/bricks.js#30]
Latest Safari, iPad
![image](https://cloud.githubusercontent.com/assets/7358151/18039750/e829e9fc-6dcf-11e6-9009-d9aadac4b79b.png)

**Comment by callmecavs** [comment]
thanks for the heads up man. closing because it's caused by #25

**Comment by callmecavs** [comment]
@andrey-hohlov fixed in the latest [release](https://github.com/callmecavs/bricks.js/releases/tag/v1.8.0), apologies for the delay
