### ISSUE TITLE
PhotoSwipe.js integration

### ISSUE THREAD

**Issue by ta69** [callmecavs/bricks.js#31]
Hi guys,

I think this library would be perfect together with [PhotoSwipe](https://github.com/dimsemenov/photoswipe), and I was hoping someone might be able to help integrate the two libraries.

Here's a working bricks.js implementation: https://jsfiddle.net/939ppbj4/21/

Here's a working photoswipe.js implementation: https://jsfiddle.net/939ppbj4/24/

Here's a non-working brick.js + photoswipe.js implementaiton: https://jsfiddle.net/939ppbj4/30/

Could someone please help figure out what's wrong? I think many people might appreciate a working example of bricks.js and photoswipe.js together.. :)

**Comment by callmecavs** [comment]
hey man - no plans to integrate with and officially support photoswipe. ive never used it, and unfortunately, know nothing about how to integrate the two. closing as this is environment specific, not an issue with Bricks
