### ISSUE TITLE
Docs: performance indicator isn't working

### ISSUE THREAD

**Issue by Narretz** [callmecavs/bricks.js#32]
It's stuck at 100ms, and refreshing the pack throws 
`bundle.js:1 Uncaught ReferenceError: nodesWidth is not defined`

**Comment by callmecavs** [comment]
see #25

**Comment by callmecavs** [comment]
@Narretz fixed in the latest [release](https://github.com/callmecavs/bricks.js/releases/tag/v1.8.0), apologies for the delay
