### ISSUE TITLE
Seems the demo is broken?

### ISSUE THREAD

**Issue by ndimatteo** [callmecavs/bricks.js#36]
@callmecavs first wanted to say this is dope!

However, when I'm on the demo site I see the following:
<img width="1440" alt="screen shot 2016-10-22 at 12 47 56 am" src="https://cloud.githubusercontent.com/assets/737188/19616982/64a1991c-97f1-11e6-9baa-e02afcb4ba56.png">

**Comment by cpmsmith** [comment]
#35 fixes this, hopefully it gets pulled at some point.

**Comment by magicspon** [comment]
Any news on when these fixes will be released

**Comment by cpmsmith** [comment]
@magicspon It doesn't look like @callmecavs has been paying much attention to the repo, but you can get a fixed version from [my fork](/cpmsmith/bricks.js).

**Comment by callmecavs** [comment]
@ndimatteo @magicspon @cpmsmith we're back, newest [release](https://github.com/callmecavs/bricks.js/releases/tag/v1.8.0) fixed it

**Comment by magicspon** [comment]
many thanks... i'll have a play soon...
