### ISSUE TITLE
Resize not working, workaround throws "nodesWidth is not defined"

### ISSUE THREAD

**Issue by roryok** [callmecavs/bricks.js#37]
The resize function doesn't consistently work for me, so I replaced it with this code

`window.addEventListener('resize', function() {`
`        instance.pack();`
`}, true);`

This throws "nodesWidth is not defined". inspecting the source, sure enough there is a line that expects a var called `nodesWidth` which doesn't exist anywhere else. Adding `var nodesWidth = 1;` to my script works

**Comment by cpmsmith** [comment]
It's a typo—it should be `nodeWidth`—and #35 fixes it.

**Comment by callmecavs** [comment]
@roryok fixed in the latest [release](https://github.com/callmecavs/bricks.js/releases/tag/v1.8.0), apologies for the delay
