### ISSUE TITLE
Timing of packing is innacurate

### ISSUE THREAD

**Issue by andrewmclagan** [callmecavs/bricks.js#4]
When placing over 100 elements into the website demo, the execution timing of the packing function is inaccurate. 

We placed 100,000 items in the demo and it stated around 1.8s when in reality we timed it around 3-4s.

**Comment by callmecavs** [comment]
@andrewmclagan all the code for the demo site lives in the [site folder](https://github.com/callmecavs/bricks.js/tree/master/site). in regards to the timing, and how I'm deriving it, you'll want to look at the [main.js](https://github.com/callmecavs/bricks.js/blob/master/site/src/js/main.js) file, and the [util.js](https://github.com/callmecavs/bricks.js/blob/master/site/src/js/util.js) file.

how did you time it? if, given the code above, you can point me in the direction of what's causing it to be inaccurate (or even better - submit a pull request that fixes the inaccuracy), I'll be happy to take a look, and correct it immediately.

don't forget that for the demo to function, the boxes first need to be created, and then injected into the DOM. that time - which may make the elapsed time seem longer than what is reported - doesn't count towards the _execution time of the library itself_. I suspect this may be what's causing the delay you're describing

**Comment by andrewmclagan** [comment]
Fair enough...

After a quick look through the issue involves the `_.times` function being called on the click event before the actual timer is executed. 

Sure your timing how long it takes to execute the **"pack"** operation, although appending the elements into the DOM (line 42 of main.js) takes quite some time. Is this operation not part of creating a grid? It seems a little out (to me) when clicking a UI element with a timing function that returns a time clearly out of sync with the actual operation?

your thoughts?

**Comment by callmecavs** [comment]
i'm only trying to time the "pack" operation, because _that's what the user is signing up for by using this library._

there are many ways to inject HTML into the DOM. some methods take much longer than others. in this case, I'm doing it efficiently, by using a document fragment. but if a user, in their grid, chose to inject each `div` individually, or alter the `innerHTML` of the container each time, the injecting could take much longer.

the way I see it, this library doesn't handle how the user's DOM gets their. it only handles styling it into a masonry grid. so that's what I'm trying to capture

**Comment by andrewmclagan** [comment]
Point taken. perhaps make that clear on the website?

**Comment by callmecavs** [comment]
i'll definitely consider it. i think for more a more realistic number of boxes, like say 100, most users wont notice a "lag" in the demo like in the case of 100,000 boxes

**Comment by andrewmclagan** [comment]
Yeah, although it was more along the lines of letting devs know they have to still be careful how they do DOM insertion i guess. Nice library BTW ;-)
