### ISSUE TITLE
Limit Numbers of Chars on Demo Input

### ISSUE THREAD

**Issue by hew** [callmecavs/bricks.js#5]
My co-worker did some testing, and input above ~100,000 will freeze the browser. This is somewhat expected, but the Pack Time option _does_ invite users to try some rather large numbers, so I would maybe limit the number of characters that can be inputted for the demo page's test.

**Comment by callmecavs** [comment]
just set a max length on the input field of 4 characters, so the max number of boxes that can be tested is 9999. thanks for the suggestion
