### ISSUE TITLE
Left To Right sorting order

### ISSUE THREAD

**Issue by AndrewSavetchuk** [callmecavs/bricks.js#51]
Hello! I need to order my grid items by "left-to-right" order. How I can reach that? 
![wqvtdgp](https://user-images.githubusercontent.com/14139435/36179891-e13538bc-1126-11e8-8878-d6b92e815c52.png)

**Comment by blakerutledge** [comment]
Youd have to write a good deal of logic yourself, i recommend forking. 

Consider the edge case where, in your example, lets say theres a 9th block that is very short, and now, you could add a 10th block below the 9th in the third column, and still not reach the bottom of 8... things could get hairy.  Thats why the lib currently picks the shortest column and stuffs the next block there.

Or - you simply go column 1-2-3-1-2-3... and you disregard the column stack height. ¯\_(ツ)_/¯

**Comment by callmecavs** [comment]
As mentioned above by @blakerutledge - this is functionality that falls outside the  scope of this module. I'd recommend using packery or isotope (whichever the screenshot comes from) as those libraries cover more options/use cases.
