### ISSUE TITLE
SyntaxError: Unexpected identifier 'Bricks'. import call expects exactly one argument.

### ISSUE THREAD

**Issue by macsupport** [callmecavs/bricks.js#55]
Using the provided, documented code, I get this error every time, _SyntaxError: Unexpected identifier 'Bricks'. import call expects exactly one argument._  and Bricks fails. I may be missing something basic but it makes no sense to set up a simple demo [ jsfiddle demo](https://jsfiddle.net/macsupport/zdy9ft1k/) with the provided Bricks code and nothing works.

**Comment by callmecavs** [comment]
@macsupport if you install `bricks.js` from NPM, the import statement should look like this:

```javascript
import Bricks from 'bricks.js'
```

if you include a script tag of the UMD file (from CDNJS or wherever) like you're doing in the JSFiddle example, `Bricks` will be available on the `window`.  using the CDN approach, there's no need to `import` anything at all.

remove the `import` from your JSFiddle and everything works as expected (as in the screenshot below).

<img width="1275" alt="screen shot 2018-06-24 at 2 45 21 pm" src="https://user-images.githubusercontent.com/2293641/41822427-790ff044-77bd-11e8-8d8e-ecf9d0d7119c.png">
