### ISSUE TITLE
Mixed Width Layouts

### ISSUE THREAD

**Issue by raphaelkross** [callmecavs/bricks.js#6]
Hi!

I would like to know about the possibility of mixed-width content, let's say one block has the double of the width used in the other blocks, is possible to get this kind of result using the current version of Bricks?

Kindly,
Rafael

**Comment by callmecavs** [comment]
@raphaelkross this library assumes all the items are fixed width, so it can't accommodate the scenario you're describing. there are definitely other solutions out there though that handle your use case. good luck!

**Comment by dmythro** [comment]
Yes, actually, would be definitely awesome to have this small, but important feature!
