### ISSUE TITLE
Suggestion about the Website background color

### ISSUE THREAD

**Issue by ajmeyghani** [callmecavs/bricks.js#9]
Awesome library! Btw, It would be great if the background color of the doc site
 was less intense. I played with the color and the `#AAAAAA` color looked cool:
<img width="500" alt="docsite" src="https://cloud.githubusercontent.com/assets/14934358/13327483/1260c4ca-dbb8-11e5-8454-2a3b0f40a27c.png">

Thanks!

**Comment by callmecavs** [comment]
@aminmeyghani I appreciate the suggestion, but I really like how bold the current color is.

**Comment by municate** [comment]
I have to say, I was going to comment on this as well a few days ago. It just burns your eyes out if you actually take time to read it; and when you go onto something else, it just stays with you... No doubt it's fun and bold and memorable, but it's a terrible design choice in this context. I'm actively avoiding returning to that tab. best

**Comment by callmecavs** [comment]
@municate agree to disagree with you on it being a "terrible design choice." thanks for the input though
